config/routes.rb
Rails.application.routes.draw do
  resources :stadia
  root to: 'stadia#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stadium.rb
class Stadium < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stadia_controller.rb
class StadiaController < ApplicationController
  before_action :set_stadium, only: %w[show edit update]
  def index
    @stadia = Stadium.order(:name)
  end

  def show; end

  def new
    @stadium = Stadium.new
  end

  def edit; end

  def create
    @stadium = Stadium.new(stadium_params)
    if @stadium.save
      flash[:success] = 'Stadium successfully saved'
      redirect_to @stadium
    else
      flash.now[:danger] = 'Error creating stadium'
      render new_stadium_path(@stadium)
    end
  end

  def update
    if @stadium.update(stadium_params)
      flash[:success] = 'Stadium successfully updated'
      redirect_to @stadium
    else
      flash.now[:danger] = 'Error updating stadium'
      redirect_to edit_stadium_path(@stadium)
    end
  end

  private

  def set_stadium
    @stadium = Stadium.find(params[:id])
  end

  def stadium_params
    params.require(:stadium).permit(:name, :image_file, :build_date, :demolition_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stadia_helper.rb
module StadiaHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Stadia
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/stadia/_form.html.haml
= form_for stadium, multipart: true do |f|
  .field.form-group
    = f.label :name
    = f.text_field :name
  .field.form-group
    = f.label :image_file
    = f.text_field :image_file
  .field.form-group
    = f.label :build_date
    = f.text_field :build_date, data: { controller: 'datepicker' }
  .field.form-group
    = f.label :demolition_date
    = f.text_field :demolition_date, data: { controller: 'datepicker' }
  .actions
    = f.submit
    = link_to 'Cancel', (stadium.persisted? ? stadium_path(stadium) : stadia_path)

app/views/stadia/edit.html.haml
%h2='Edit stadium'
= render partial: 'form', locals: { stadium: @stadium }

app/views/stadia/index.html.haml
%div{ 'data-controller' => 'slideshow', 'data-slideshow-index' => '0' }
  - @stadia.each do |stadium|
    .slide{ 'data-target' => 'slideshow.slide' }
      %h2
        = stadium.name
      = image_pack_tag stadium.image_file, size: '800x500'
  %button.previous{ 'data-action' => 'slideshow#previous' } Previous
  %button.next{ 'data-action' => 'slideshow#next' } Next

app/views/stadia/new.html.haml
%h2='New stadium'
= render partial: 'form', locals: { stadium: @stadium }

app/views/stadia/show.html.haml
%h2
  = @stadium.name
.row
  .col.py-2
    %b= 'Build Date'
  .col.py-2
    = @stadium.build_date
.row
  .col.py-2
    %b= 'Demolition Date'
  .col.py-2
    = @stadium.build_date
.row
  = image_pack_tag @stadium.image_file, size: '800x500'
.row
  = link_to 'Edit', edit_stadium_path(@stadium)